# This workflow will install Python dependencies, run tests and lint. It will then deploy to CapRover.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flask application

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test
      run: |
        pip install .[test]
        pytest

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy App to ImPaaS
      run: |
        curl --location --request \
        POST 'http://impaas.uk/apps/${{ vars.APP_NAME }}/deploy?image=ghcr.io%2Faaryan-dharmadhikari%2Fflask-template%3Av1' \
        --header 'Authorization: Bearer ${{ secrets.TEAM_DEPLOYMENT_TOKEN }}'